# Generated by Django 3.1.5 on 2021-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
