# Generated by Django 3.1.5 on 2021-01-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orders_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
